AZURE_OPENAI_BASE ='https://newresourcegro1671500602.openai.azure.com/'
AZURE_OPENAI_KEY = "f5fd102226d34a35bf846acd0c8bfb9b"
AZURE_OPENAI_VERSION = '2024-05-01-preview'
AZURE_OPENAI_DEPLOYMENT_NAME = 'gpt-35-turbo-16k'

PROMPTFLOW_ENDPOINT_URL = 'https://fabric-sql-generator.eastus2.inference.ml.azure.com/score'
PROMPTFLOW_ENDPOINT_KEY = 'kTjhVpLTLRgSa14gtmCZ4IpKFY8h5TxV'

FABRIC_USERNAME = "yrlee@zalesia.co.kr"
FABRIC_PASSWORD = "71040101yr*^^*"
FABRIC_ENDPOINT = "ewcih6goojaerchrwjcdkqtqwu-ey5yqgnsqisefmnb3wo4nxmhiu.datawarehouse.fabric.microsoft.com"
FABRIC_DATABASE = "DWforAiStudio"